//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioMit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiblioMit.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Ausencia.
        /// </summary>
        internal static string Degree_d0 {
            get {
                return ResourceManager.GetString("Degree_d0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Presentes.
        /// </summary>
        internal static string Degree_d11 {
            get {
                return ResourceManager.GetString("Degree_d11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Frecuentes.
        /// </summary>
        internal static string Degree_d21 {
            get {
                return ResourceManager.GetString("Degree_d21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Abundantes.
        /// </summary>
        internal static string Degree_d31 {
            get {
                return ResourceManager.GetString("Degree_d31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100X.
        /// </summary>
        internal static string Magnification_mag100x1 {
            get {
                return ResourceManager.GetString("Magnification_mag100x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10X.
        /// </summary>
        internal static string Magnification_mag10x {
            get {
                return ResourceManager.GetString("Magnification_mag10x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20X.
        /// </summary>
        internal static string Magnification_mag20x1 {
            get {
                return ResourceManager.GetString("Magnification_mag20x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40X.
        /// </summary>
        internal static string Magnification_mag40x {
            get {
                return ResourceManager.GetString("Magnification_mag40x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5X.
        /// </summary>
        internal static string Magnification_mag5x {
            get {
                return ResourceManager.GetString("Magnification_mag5x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En desarrollo.
        /// </summary>
        internal static string Maturity_Developing {
            get {
                return ResourceManager.GetString("Maturity_Developing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maduro.
        /// </summary>
        internal static string Maturity_Mature {
            get {
                return ResourceManager.GetString("Maturity_Mature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-desove.
        /// </summary>
        internal static string Maturity_PostSpawning {
            get {
                return ResourceManager.GetString("Maturity_PostSpawning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desove.
        /// </summary>
        internal static string Maturity_Spawning {
            get {
                return ResourceManager.GetString("Maturity_Spawning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminado.
        /// </summary>
        internal static string Maturity_Undetermined {
            get {
                return ResourceManager.GetString("Maturity_Undetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hembra.
        /// </summary>
        internal static string Sex_Female {
            get {
                return ResourceManager.GetString("Sex_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermafrodita.
        /// </summary>
        internal static string Sex_Hermaphrodite {
            get {
                return ResourceManager.GetString("Sex_Hermaphrodite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macho.
        /// </summary>
        internal static string Sex_Male {
            get {
                return ResourceManager.GetString("Sex_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminado.
        /// </summary>
        internal static string Sex_Undetermined {
            get {
                return ResourceManager.GetString("Sex_Undetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absceso.
        /// </summary>
        internal static string SoftType_Abscess {
            get {
                return ResourceManager.GetString("SoftType_Abscess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gónada atrésica.
        /// </summary>
        internal static string SoftType_Atresia {
            get {
                return ResourceManager.GetString("SoftType_Atresia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciliados.
        /// </summary>
        internal static string SoftType_Ciliates {
            get {
                return ResourceManager.GetString("SoftType_Ciliates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copépodo.
        /// </summary>
        internal static string SoftType_Copepod {
            get {
                return ResourceManager.GetString("SoftType_Copepod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neoplasia.
        /// </summary>
        internal static string SoftType_DN {
            get {
                return ResourceManager.GetString("SoftType_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infiltración hemocítica.
        /// </summary>
        internal static string SoftType_HaemocyticInfiltration {
            get {
                return ResourceManager.GetString("SoftType_HaemocyticInfiltration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Hallazgos.
        /// </summary>
        internal static string SoftType_Healthy {
            get {
                return ResourceManager.GetString("SoftType_Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lipofucsina.
        /// </summary>
        internal static string SoftType_Lipofuscin {
            get {
                return ResourceManager.GetString("SoftType_Lipofuscin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsporidios.
        /// </summary>
        internal static string SoftType_Microsporidia {
            get {
                return ResourceManager.GetString("SoftType_Microsporidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rickettsiales.
        /// </summary>
        internal static string SoftType_RLO {
            get {
                return ResourceManager.GetString("SoftType_RLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tremátodo.
        /// </summary>
        internal static string SoftType_Trematode {
            get {
                return ResourceManager.GetString("SoftType_Trematode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso que ingresa un agente y está disponible para comercialización y/o transformación..
        /// </summary>
        internal static string Tipo_Abastecimiento_Description {
            get {
                return ResourceManager.GetString("Tipo_Abastecimiento_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planta.
        /// </summary>
        internal static string Tipo_Abastecimiento_GroupName {
            get {
                return ResourceManager.GetString("Tipo_Abastecimiento_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abastecimiento Plantas.
        /// </summary>
        internal static string Tipo_Abastecimiento_Name {
            get {
                return ResourceManager.GetString("Tipo_Abastecimiento_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toneladas.
        /// </summary>
        internal static string Tipo_Abastecimiento_Prompt {
            get {
                return ResourceManager.GetString("Tipo_Abastecimiento_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad extractiva que se realiza en los centros de acuicultura a fin de obtener un producto para su posterior comercialización..
        /// </summary>
        internal static string Tipo_Cosecha_Description {
            get {
                return ResourceManager.GetString("Tipo_Cosecha_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        internal static string Tipo_Cosecha_GroupName {
            get {
                return ResourceManager.GetString("Tipo_Cosecha_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosecha Adultos.
        /// </summary>
        internal static string Tipo_Cosecha_Name {
            get {
                return ResourceManager.GetString("Tipo_Cosecha_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toneladas.
        /// </summary>
        internal static string Tipo_Cosecha_Prompt {
            get {
                return ResourceManager.GetString("Tipo_Cosecha_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso neto de productos obtenidos a partir de una materia prima, mediante un proceso de elaboración..
        /// </summary>
        internal static string Tipo_Producción_Description {
            get {
                return ResourceManager.GetString("Tipo_Producción_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planta.
        /// </summary>
        internal static string Tipo_Producción_GroupName {
            get {
                return ResourceManager.GetString("Tipo_Producción_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción de Plantas de Elaboración.
        /// </summary>
        internal static string Tipo_Producción_Name {
            get {
                return ResourceManager.GetString("Tipo_Producción_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toneladas.
        /// </summary>
        internal static string Tipo_Producción_Prompt {
            get {
                return ResourceManager.GetString("Tipo_Producción_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad relativa de sales disueltas (gr) en un cuerpo de agua (L) medida en Practical Salinity Units (PSU) definidas como 35 gr de sal / Lt de agua..
        /// </summary>
        internal static string Tipo_Salinidad_Description {
            get {
                return ResourceManager.GetString("Tipo_Salinidad_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiental.
        /// </summary>
        internal static string Tipo_Salinidad_GroupName {
            get {
                return ResourceManager.GetString("Tipo_Salinidad_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinidad.
        /// </summary>
        internal static string Tipo_Salinidad_Name {
            get {
                return ResourceManager.GetString("Tipo_Salinidad_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSU - Practical Salinity Units.
        /// </summary>
        internal static string Tipo_Salinidad_Prompt {
            get {
                return ResourceManager.GetString("Tipo_Salinidad_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción que tiene por objeto la fijación de larvas de invertebrados mediante la disposición de colectores..
        /// </summary>
        internal static string Tipo_Semilla_Description {
            get {
                return ResourceManager.GetString("Tipo_Semilla_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        internal static string Tipo_Semilla_GroupName {
            get {
                return ResourceManager.GetString("Tipo_Semilla_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captación de Semillas.
        /// </summary>
        internal static string Tipo_Semilla_Name {
            get {
                return ResourceManager.GetString("Tipo_Semilla_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toneladas.
        /// </summary>
        internal static string Tipo_Semilla_Prompt {
            get {
                return ResourceManager.GetString("Tipo_Semilla_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corresponde a la interfase de intercambio de calor entre la atmófera y el océano. En términos prácticos, el significado de &apos;superficie&apos; variará de acuerdo al método de medida usado para la determinación de la temperatura..
        /// </summary>
        internal static string Tipo_Temperatura_Description {
            get {
                return ResourceManager.GetString("Tipo_Temperatura_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiental.
        /// </summary>
        internal static string Tipo_Temperatura_GroupName {
            get {
                return ResourceManager.GetString("Tipo_Temperatura_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura Superficial.
        /// </summary>
        internal static string Tipo_Temperatura_Name {
            get {
                return ResourceManager.GetString("Tipo_Temperatura_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSM - Temperatura Superficial del Mar.
        /// </summary>
        internal static string Tipo_Temperatura_Prompt {
            get {
                return ResourceManager.GetString("Tipo_Temperatura_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glándula digestiva.
        /// </summary>
        internal static string Tissue_DigestiveGland {
            get {
                return ResourceManager.GetString("Tissue_DigestiveGland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        internal static string Tissue_Foot {
            get {
                return ResourceManager.GetString("Tissue_Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branquias.
        /// </summary>
        internal static string Tissue_Gill {
            get {
                return ResourceManager.GetString("Tissue_Gill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gónada.
        /// </summary>
        internal static string Tissue_Gonad {
            get {
                return ResourceManager.GetString("Tissue_Gonad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intestino.
        /// </summary>
        internal static string Tissue_Intestine {
            get {
                return ResourceManager.GetString("Tissue_Intestine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manto.
        /// </summary>
        internal static string Tissue_Mantle {
            get {
                return ResourceManager.GetString("Tissue_Mantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nefridio.
        /// </summary>
        internal static string Tissue_Nephridium {
            get {
                return ResourceManager.GetString("Tissue_Nephridium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membrana plicada.
        /// </summary>
        internal static string Tissue_PlicateMembrane {
            get {
                return ResourceManager.GetString("Tissue_PlicateMembrane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saco del estilete.
        /// </summary>
        internal static string Tissue_StyleSac {
            get {
                return ResourceManager.GetString("Tissue_StyleSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Túbulos.
        /// </summary>
        internal static string Tissue_Tubules {
            get {
                return ResourceManager.GetString("Tissue_Tubules", resourceCulture);
            }
        }
    }
}
